### ISSUE TITLE
Pattern de Commits ⚡

### ISSUE THREAD

**Issue by ghost** [antonioal97/imobiliaria-imoveis#9]
Olá tudo bem? 

Vi que seu projeto segue um padrão do GitFlow, metodologia de branchs.

Uma coisa interessante que você poderia ver para complementar era sobre os Pattern de Commits. 😉

~~Obs: achei que não tinha uma preview, depois vi a branch develop 🤣~~

**Comment by correantonio** [comment]
Obrigado pelo feedback kkkk
Eu estou começando a implementar essa metodologia de branchs para organização. Fiz o deploy do site no Vercel, gosto bastante de lá kkk
